export const PROJECTS = [
  {
    id: 1,
    title: "Puma middle east",
    alt: "PUMA",
    cover: "/Projects/images/PUMA/PUMAHERO.jpg",
    images: [
      "/Projects/images/PUMA/PUMA2.jpg",
      "/Projects/images/PUMA/PUMA3.jpg",
      "/Projects/images/PUMA/PUMA4.webp",
      "/Projects/images/PUMA/PUMA5.webp",
      "/Projects/images/PUMA/PUMA6.webp",
      "/Projects/images/PUMA/PUMA7.webp",
      "/Projects/images/PUMA/PUMA8.webp",
      "/Projects/images/PUMA/PUMA9.webp",
      "/Projects/images/PUMA/PUMA10.webp",
    ],
    link:"https://www.behance.net/gallery/233148841/Puma-middle-east",
    date: "2024",
    description: "Exploring emotion through natural light.",
  },
  {
    id: 2,
    title: "Porsh-ley Perfect",
    alt: "porsche",
    cover: "/Projects/images/PORSCHE/PORSCHE.jpg",
    images: [
      "Projects/images/PUMA/PUMA2.jpg",
      "Projects/images/PUMA/PUMA3.jpg",
      "Projects/images/PUMA/PUMA4.webp",
      "Projects/images/PUMA/PUMA5.webp",
      "Projects/images/PUMA/PUMA6.webp",
      "Projects/images/PUMA/PUMA7.webp",
      "Projects/images/PUMA/PUMA8.webp",
      "Projects/images/PUMA/PUMA9.webp",
      "Projects/images/PUMA/PUMA10.webp",
    ],
    link:"https://www.behance.net/gallery/210660637/Porsh-ley-Perfect",
    date: "2024",
    description: "Exploring emotion through natural light.",
  },
  {
    id: 3,
    title: "Adidas Dubai - Strength Collection",
    alt: "adidas",
    cover: "/Projects/images/Adidas/Adidas.jpg",
    images: [
      "Projects/images/PUMA/PUMA2.jpg",
      "Projects/images/PUMA/PUMA3.jpg",
      "Projects/images/PUMA/PUMA4.webp",
      "Projects/images/PUMA/PUMA5.webp",
      "Projects/images/PUMA/PUMA6.webp",
      "Projects/images/PUMA/PUMA7.webp",
      "Projects/images/PUMA/PUMA8.webp",
      "Projects/images/PUMA/PUMA9.webp",
      "Projects/images/PUMA/PUMA10.webp",
    ],
    link:"https://www.behance.net/gallery/202245933/Adidas-Dubai-Strength-Collection",
    date:"2025",
    description: "Exploring emotion through natural light.",
  },
  {
    id: 4,
    title: "Mirage - Ferrari x Dubai",
    alt: "mirage ferrari",
    cover: "/Projects/images/CAR/CAR.jpg",
    images: [
      "Projects/images/PUMA/PUMA2.jpg",
      "Projects/images/PUMA/PUMA3.jpg",
      "Projects/images/PUMA/PUMA4.webp",
      "Projects/images/PUMA/PUMA5.webp",
      "Projects/images/PUMA/PUMA6.webp",
      "Projects/images/PUMA/PUMA7.webp",
      "Projects/images/PUMA/PUMA8.webp",
      "Projects/images/PUMA/PUMA9.webp",
      "Projects/images/PUMA/PUMA10.webp",
    ],
    description: "Exploring emotion through natural light.",
  },
  {
    id: 5,
    title: "VOX CINEMA - MALL OF THE EMIRATES, UAE",
    alt: "vox cinema",
    cover: "/Projects/images/CINEMA/CINEMA.jpg",
    images: [
      "Projects/images/PUMA/PUMA2.jpg",
      "Projects/images/PUMA/PUMA3.jpg",
      "Projects/images/PUMA/PUMA4.webp",
      "Projects/images/PUMA/PUMA5.webp",
      "Projects/images/PUMA/PUMA6.webp",
      "Projects/images/PUMA/PUMA7.webp",
      "Projects/images/PUMA/PUMA8.webp",
      "Projects/images/PUMA/PUMA9.webp",
      "Projects/images/PUMA/PUMA10.webp",
    ],
    link:"https://www.behance.net/gallery/190680523/VOX-CINEMA-MALL-OF-THE-EMIRATES-UAE",
    date:"2025",
    description: "Exploring emotion through natural light.",
  },
  {
    id: 7,
    title: "Talise",
    alt: "talise",
    cover: "/Projects/images/TALISE/TALISEHERO.webp",
    images: [
      "Projects/images/PUMA/PUMA2.jpg",
      "Projects/images/PUMA/PUMA3.jpg",
      "Projects/images/PUMA/PUMA4.webp",
      "Projects/images/PUMA/PUMA5.webp",
      "Projects/images/PUMA/PUMA6.webp",
      "Projects/images/PUMA/PUMA7.webp",
      "Projects/images/PUMA/PUMA8.webp",
      "Projects/images/PUMA/PUMA9.webp",
      "Projects/images/PUMA/PUMA10.webp",
    ],
    link:"https://www.behance.net/gallery/215363305/Talise",
    date:"2025",
    description: "Exploring emotion through natural light.",
  },
  {
    id: 8,
    title: "Jumeirah Dar Al Masyaf",
    alt: "Jumeria",
    cover: "/Projects/images/Jumeriah/JumeriahHERO.jpg",
    images: [
      "Projects/images/PUMA/PUMA2.jpg",
      "Projects/images/PUMA/PUMA3.jpg",
      "Projects/images/PUMA/PUMA4.webp",
      "Projects/images/PUMA/PUMA5.webp",
      "Projects/images/PUMA/PUMA6.webp",
      "Projects/images/PUMA/PUMA7.webp",
      "Projects/images/PUMA/PUMA8.webp",
      "Projects/images/PUMA/PUMA9.webp",
      "Projects/images/PUMA/PUMA10.webp",
    ],
    link:"https://www.behance.net/gallery/214789363/Jumeirah-Dar-Al-Masyaf",
    date:"2024",
    description: "Exploring emotion through natural light.",
  },
  {
    id: 9,
    title: "Jumeirah Mina Al Salam",
    alt: "Jumeriah",
    cover: "/Projects/images/Jumeriah2/JumeriahHero.webp",
    images: [
      "Projects/images/PUMA/PUMA2.jpg",
      "Projects/images/PUMA/PUMA3.jpg",
      "Projects/images/PUMA/PUMA4.webp",
      "Projects/images/PUMA/PUMA5.webp",
      "Projects/images/PUMA/PUMA6.webp",
      "Projects/images/PUMA/PUMA7.webp",
      "Projects/images/PUMA/PUMA8.webp",
      "Projects/images/PUMA/PUMA9.webp",
      "Projects/images/PUMA/PUMA10.webp",
    ],
    link:"https://www.behance.net/gallery/202634557/Jumeirah-Mina-Al-Salam",
    date:"2025",
    description: "Exploring emotion through natural light.",
  },
  {
    id: 10,
    title: "Ganache Chocolatier",
    alt: "GANACHE",
    cover: "/Projects/images/Ganache/Ganache.jpg",
    images: [
      "Projects/images/PUMA/PUMA2.jpg",
      "Projects/images/PUMA/PUMA3.jpg",
      "Projects/images/PUMA/PUMA4.webp",
      "Projects/images/PUMA/PUMA5.webp",
      "Projects/images/PUMA/PUMA6.webp",
      "Projects/images/PUMA/PUMA7.webp",
      "Projects/images/PUMA/PUMA8.webp",
      "Projects/images/PUMA/PUMA9.webp",
      "Projects/images/PUMA/PUMA10.webp",
    ],
    description: "Exploring emotion through natural light.",
  },
  {
    id: 11,
    title: "THE ART OF AlUla - SAUDI ARABIA",
    alt: "ALULA",
    cover: "/Projects/images/ALULA/ALULA.jpg",
    images: [
      "Projects/images/PUMA/PUMA2.jpg",
      "Projects/images/PUMA/PUMA3.jpg",
      "Projects/images/PUMA/PUMA4.webp",
      "Projects/images/PUMA/PUMA5.webp",
      "Projects/images/PUMA/PUMA6.webp",
      "Projects/images/PUMA/PUMA7.webp",
      "Projects/images/PUMA/PUMA8.webp",
      "Projects/images/PUMA/PUMA9.webp",
      "Projects/images/PUMA/PUMA10.webp",
    ],
    description: "Exploring emotion through natural light.",
  },
  {
    id: 12,
    title: "STARYOUTH",
    alt: "STARYOUTH",
    cover: "/Projects/images/staryouth/staryouth.jpg",
    images: [
      "Projects/images/PUMA/PUMA2.jpg",
      "Projects/images/PUMA/PUMA3.jpg",
      "Projects/images/PUMA/PUMA4.webp",
      "Projects/images/PUMA/PUMA5.webp",
      "Projects/images/PUMA/PUMA6.webp",
      "Projects/images/PUMA/PUMA7.webp",
      "Projects/images/PUMA/PUMA8.webp",
      "Projects/images/PUMA/PUMA9.webp",
      "Projects/images/PUMA/PUMA10.webp",
    ],
    description: "Exploring emotion through natural light.",
  },
  {
    id: 13,
    title: "The Art Of Jumeirah",
    alt: "Jumeriah",
    cover: "/Projects/images/Jumeriah3/Jumeriah.jpg",
    images: [
      "Projects/images/PUMA/PUMA2.jpg",
      "Projects/images/PUMA/PUMA3.jpg",
      "Projects/images/PUMA/PUMA4.webp",
      "Projects/images/PUMA/PUMA5.webp",
      "Projects/images/PUMA/PUMA6.webp",
      "Projects/images/PUMA/PUMA7.webp",
      "Projects/images/PUMA/PUMA8.webp",
      "Projects/images/PUMA/PUMA9.webp",
      "Projects/images/PUMA/PUMA10.webp",
    ],
    description: "Exploring emotion through natural light.",
  },
  {
    id: 14,
    title: "Bare",
    alt: "rang",
    cover: "/Projects/images/Bare/BARE.jpg",
    images: [
      "Projects/images/PUMA/PUMA2.jpg",
      "Projects/images/PUMA/PUMA3.jpg",
      "Projects/images/PUMA/PUMA4.webp",
      "Projects/images/PUMA/PUMA5.webp",
      "Projects/images/PUMA/PUMA6.webp",
      "Projects/images/PUMA/PUMA7.webp",
      "Projects/images/PUMA/PUMA8.webp",
      "Projects/images/PUMA/PUMA9.webp",
      "Projects/images/PUMA/PUMA10.webp",
    ],
    description: "Exploring emotion through natural light.",
  },
  {
    id: 15,
    title: "Future Horizons",
    alt: "Future Horizons",
    cover: "/Projects/images/Circle/Circle.jpg",
    images: [
      "Projects/images/PUMA/PUMA2.jpg",
      "Projects/images/PUMA/PUMA3.jpg",
      "Projects/images/PUMA/PUMA4.webp",
      "Projects/images/PUMA/PUMA5.webp",
      "Projects/images/PUMA/PUMA6.webp",
      "Projects/images/PUMA/PUMA7.webp",
      "Projects/images/PUMA/PUMA8.webp",
      "Projects/images/PUMA/PUMA9.webp",
      "Projects/images/PUMA/PUMA10.webp",
    ],
    description: "Exploring emotion through natural light.",
  },
  {
    id: 16,
    title: "Apocalypse",
    alt:"apocalypse",
    cover: "/Projects/images/BLACK/Black.jpg",
    images: [
      "Projects/images/PUMA/PUMA2.jpg",
      "Projects/images/PUMA/PUMA3.jpg",
      "Projects/images/PUMA/PUMA4.webp",
      "Projects/images/PUMA/PUMA5.webp",
      "Projects/images/PUMA/PUMA6.webp",
      "Projects/images/PUMA/PUMA7.webp",
      "Projects/images/PUMA/PUMA8.webp",
      "Projects/images/PUMA/PUMA9.webp",
      "Projects/images/PUMA/PUMA10.webp",
    ],
    description: "Exploring emotion through natural light.",
  },
  {
    id: 17,
    title: "@arsenal X @adidasfootball",
    alt:"ARSENAL X ADIDAS",
    cover: "/Projects/images/ARSENAL/ARSENALHERO.jpg",
    images: [
      "Projects/images/PUMA/PUMA2.jpg",
      "Projects/images/PUMA/PUMA3.jpg",
      "Projects/images/PUMA/PUMA4.webp",
      "Projects/images/PUMA/PUMA5.webp",
      "Projects/images/PUMA/PUMA6.webp",
      "Projects/images/PUMA/PUMA7.webp",
      "Projects/images/PUMA/PUMA8.webp",
      "Projects/images/PUMA/PUMA9.webp",
      "Projects/images/PUMA/PUMA10.webp",
    ],
    link:"https://www.behance.net/gallery/231767115/arsenal-X-adidasfootball",
    date:"2025",
    description: "Exploring emotion through natural light.",
  },
  
  {
    id: 18,
    title: "Disconected",
    alt:"disconected",
    cover: "/Projects/images/Disconected/disconected.jpg",
    images: [
      "Projects/images/PUMA/PUMA2.jpg",
      "Projects/images/PUMA/PUMA3.jpg",
      "Projects/images/PUMA/PUMA4.webp",
      "Projects/images/PUMA/PUMA5.webp",
      "Projects/images/PUMA/PUMA6.webp",
      "Projects/images/PUMA/PUMA7.webp",
      "Projects/images/PUMA/PUMA8.webp",
      "Projects/images/PUMA/PUMA9.webp",
      "Projects/images/PUMA/PUMA10.webp",
    ],
    description: "Exploring emotion through natural light.",
  },
  {
    id: 19,
    title: "Heaven",
    alt:"Heaven",
    cover: "/Projects/images/WHITE/White.png",
    images: [
      "Projects/images/PUMA/PUMA2.jpg",
      "Projects/images/PUMA/PUMA3.jpg",
      "Projects/images/PUMA/PUMA4.webp",
      "Projects/images/PUMA/PUMA5.webp",
      "Projects/images/PUMA/PUMA6.webp",
      "Projects/images/PUMA/PUMA7.webp",
      "Projects/images/PUMA/PUMA8.webp",
      "Projects/images/PUMA/PUMA9.webp",
      "Projects/images/PUMA/PUMA10.webp",
    ],
    description: "Exploring emotion through natural light.",
  },
  {
    id: 20,
    title: "MOODY GIRL",
    alt:"MOODY GIRL",
    cover: "/Projects/images/TEA/TEA.jpg",
    images: [
      "Projects/images/PUMA/PUMA2.jpg",
      "Projects/images/PUMA/PUMA3.jpg",
      "Projects/images/PUMA/PUMA4.webp",
      "Projects/images/PUMA/PUMA5.webp",
      "Projects/images/PUMA/PUMA6.webp",
      "Projects/images/PUMA/PUMA7.webp",
      "Projects/images/PUMA/PUMA8.webp",
      "Projects/images/PUMA/PUMA9.webp",
      "Projects/images/PUMA/PUMA10.webp",
    ],
    description: "Exploring emotion through natural light.",
  },
  {
    id: 21,
    title: "Fitness Photography - Adidas",
    alt: "Adidas",
    cover: "/Projects/images/Adidas2/Adidas2.webp",
    images: [
      "Projects/images/PUMA/PUMA2.jpg",
      "Projects/images/PUMA/PUMA3.jpg",
      "Projects/images/PUMA/PUMA4.webp",
      "Projects/images/PUMA/PUMA5.webp",
      "Projects/images/PUMA/PUMA6.webp",
      "Projects/images/PUMA/PUMA7.webp",
      "Projects/images/PUMA/PUMA8.webp",
      "Projects/images/PUMA/PUMA9.webp",
      "Projects/images/PUMA/PUMA10.webp",
    ],
    link:"https://www.behance.net/gallery/202242347/Fitness-Photography",
    date:"2024",
    description: "Exploring emotion through natural light.",
  },
  {
    id: 22,
    title: "PEET'S COFFEE - DUBAI HILLS MALL",
    alt: "PEET'S COFFEE",
    cover: "/Projects/images/PEET/PeetHero.jpg",
    images: [
      "Projects/images/PUMA/PUMA2.jpg",
      "Projects/images/PUMA/PUMA3.jpg",
      "Projects/images/PUMA/PUMA4.webp",
      "Projects/images/PUMA/PUMA5.webp",
      "Projects/images/PUMA/PUMA6.webp",
      "Projects/images/PUMA/PUMA7.webp",
      "Projects/images/PUMA/PUMA8.webp",
      "Projects/images/PUMA/PUMA9.webp",
      "Projects/images/PUMA/PUMA10.webp",
    ],
    description: "Exploring emotion through natural light.",
  },
  {
    id: 23,
    title: "Desert Runner - Adidas x David Popa",
    alt:"Adidas",
    cover: "/Projects/images/Adidas3/Adidas.jpg",
    images: [
      "Projects/images/PUMA/PUMA2.jpg",
      "Projects/images/PUMA/PUMA3.jpg",
      "Projects/images/PUMA/PUMA4.webp",
      "Projects/images/PUMA/PUMA5.webp",
      "Projects/images/PUMA/PUMA6.webp",
      "Projects/images/PUMA/PUMA7.webp",
      "Projects/images/PUMA/PUMA8.webp",
      "Projects/images/PUMA/PUMA9.webp",
      "Projects/images/PUMA/PUMA10.webp",
    ],
    link:"https://www.behance.net/gallery/220924899/Desert-Runner-Adidas-x-David-Popa",
    date:"2025",
    description: "Exploring emotion through natural light.",
  },
  {
    id: 24,
    title: "CUBE",
    alt:"Cube",
    cover: "/Projects/images/Cube/Cube.jpg",
    images: [
      "Projects/images/PUMA/PUMA2.jpg",
      "Projects/images/PUMA/PUMA3.jpg",
      "Projects/images/PUMA/PUMA4.webp",
      "Projects/images/PUMA/PUMA5.webp",
      "Projects/images/PUMA/PUMA6.webp",
      "Projects/images/PUMA/PUMA7.webp",
      "Projects/images/PUMA/PUMA8.webp",
      "Projects/images/PUMA/PUMA9.webp",
      "Projects/images/PUMA/PUMA10.webp",
    ],
    description: "Exploring emotion through natural light.",
  },
  {
    id: 6,
    title: "Night Crawler",
    alt:"Cube",
    cover: "/Projects/images/Night Crawler/Night Crawler.webp",
    images: [
      "Projects/images/PUMA/PUMA2.jpg",
      "Projects/images/PUMA/PUMA3.jpg",
      "Projects/images/PUMA/PUMA4.webp",
      "Projects/images/PUMA/PUMA5.webp",
      "Projects/images/PUMA/PUMA6.webp",
      "Projects/images/PUMA/PUMA7.webp",
      "Projects/images/PUMA/PUMA8.webp",
      "Projects/images/PUMA/PUMA9.webp",
      "Projects/images/PUMA/PUMA10.webp",
    ],
    description: "Exploring emotion through natural light.",
  },
  
];
